# --- H2 Database (Commented Out) ---
# spring.datasource.url=jdbc:h2:file:./data/vehiclerentaldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- Microsoft SQL Server Configuration ---
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=vehiclerental_db;encrypt=true;trustServerCertificate=true;}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.properties.hibernate.hbm2ddl.jdbc_metadata_extraction_strategy=grouped
spring.jpa.properties.hibernate.jdbc.lock_timeout=30000
spring.jpa.show-sql=true
server.port=${PORT:8080}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Enable CORS for Vite React app
spring.web.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Increase payload limits for Base64 image uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Actuator Configuration
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
info.app.name=Vehicle Rental API
info.app.version=1.0.0

# Cache Configuration (Disabled Redis for local dev)
spring.cache.type=${CACHE_TYPE:none}
spring.data.redis.repositories.enabled=${REDIS_ENABLED:false}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# UPI Configuration
upi.vpa=${UPI_VPA}
upi.name=RideNest Rental

# Spring boot Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# google Auth
google.client.id=${GOOGLE_CLIENT_ID}

# Driving Licence Verification

file.upload-dir=${FILE_UPLOAD_DIR:uploads/licenses}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
